sudo: false

branches:
  only:
    - tres_tramos
    - master

addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - dia


script:

  - cd scripts/
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    all_branches: true
    #branch: tres_tramos