sudo: false

branches:
  only:
    - tres_tramos

addons:
  apt:
    packages:
      - doxygen
      - graphviz


script:

  - cd scripts/
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: tres_tramos